CREATE DATABASE notes_app;
USE notes_app;

CREATE TABLE login (
  id integer PRIMARY KEY AUTO_INCREMENT,
  user VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT NOW()
);